(defparameter *sum* 3)
(defparameter *upper-limit* 4000000)
(defparameter *a* 1)
(defparameter *b* 2)

(defun next_fib()
  (let ((n_fib (+ *a* *b*)))  
    (cond ((< n_fib *upper-limit*)
           (setf *a* *b*)porp()
    	   (setf *b* n_fib)
           (unless (oddp n_fib)
	           	   (setf *sum* (+ n_fib *sum*)))
           (next_fib)))))

(next_fib)
(print *sum*)