(defvar *sum* 0)
(defvar *lower-limit* 0)
(defvar *upper-limit* 1000)

(defun 3-or-5-divisor(int)
  (cond ((eq *lower-limit* int) '0)
  		((or (eq (mod int 3) 0) 
       		 (eq (mod int 5) 0))
       		      (setf *sum* (+ *sum* int ))
            	  (3-and-5-divisor (1- int)))
    	(t 	  (3-and-5-divisor(1- int)))))
  
(setf *sum* 0)
(3-or-5-divisor 999)
(print *sum*)